apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abcapp
  name: abcapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abcapp
  template:
    metadata:
      labels:
        app: abcapp
    spec:
      containers:
        - image: grbsntcs/abctech:v28
          name: abcapp
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: abc-service
spec:
  type: NodePort
  selector:
      app: abcapp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8080
